// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "angy boi":return img`
. . . . . . . . . b 5 b . . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 b c 5 5 d 4 c . . 
. b b b b 5 5 5 1 f d d 4 4 4 b 
. b d 5 b 5 5 b c b 4 4 4 4 b . 
. . b 5 5 b 5 5 5 4 e e e b . . 
. . b d 5 5 b 5 5 5 4 4 4 4 . . 
. b d b 5 5 5 d 5 5 5 5 4 4 4 . 
b d d c d 5 5 b 5 5 5 5 5 5 b . 
c d d d c c b 5 5 5 5 5 5 5 b . 
c b d d d d d 5 5 5 5 5 5 5 b . 
. c d d d d d d 5 5 5 5 5 d b . 
. . c b d d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
            case "image2":
            case "thing":return img`
. . . . . . . . . . . . . . . . 
. . . . b b b . . . . . . . . . 
. . . b b b d d b b b b . . . . 
. . . b b b d d d d b b b b . . 
. . b b b b b b d d b b d d . . 
. b b d d b b b b b b b d d . . 
. b d d b b b b b b b b b . . . 
b b d d b b b 1 1 1 1 1 . . . . 
b b d d b 1 1 1 1 f f 1 1 . . . 
b b b b 1 1 1 1 1 1 1 1 1 . . . 
b b b . 1 1 1 1 1 f 1 1 . . . . 
. . . . 1 1 1 1 1 1 f f . . . . 
. . . . 1 1 1 1 1 1 1 1 . . . . 
. . . . . 1 1 1 1 1 1 . . . . . 
. . . . . . 1 . . 1 . . . . . . 
. . . . . . 1 1 . 1 1 . . . . . 
`;
            case "image3":
            case "big boi":return img`
..............................
.................e............
.................5............
.................5e...........
.................eeee5........
.................555ef5e5e....
.................e5e55e5e5....
.................555555555....
.................5ee55555.....
.................55...........
.................55...........
.................e5...........
.................e5...........
.................55...........
.................55...........
.................5e...........
................5ee...........
...........55555555...........
.......5555eeee555ee..........
......55555eeeee55ee..........
....5e555555eeee55ee..........
...5555eee5555555555..........
...5.e5eee555555555...........
...5.5555555555555............
..55...555555555..............
..5.....5e....e5..............
..e.....ee....ee..............
..e.....55....e5..............
........55....55..............
........55....55..............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
